SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS `public_utility_billing_system`;
USE `public_utility_billing_system`;

-- 1. REFERENCE AND CORE LOOKUP TABLES (R1 - R2)

DROP TABLE IF EXISTS `REF_UTILITY_TYPE`;
CREATE TABLE `REF_UTILITY_TYPE` (
    `UTILITY_TYPE_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `UTILITY_TYPE_NAME` VARCHAR(50) NOT NULL UNIQUE,
    `DESCRIPTION` VARCHAR(255),
    `UNIT_OF_MEASURE` VARCHAR(20) NOT NULL,
    `CREATED_DATE` DATE NOT NULL,
    `MODIFIED_DATE` DATE,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `DEPARTMENT`;
CREATE TABLE `DEPARTMENT` (
    `DEPARTMENT_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DEPARTMENT_NAME` VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;

-- 2. CORE RECORDS (C3 - C8)

DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (
    `EMPLOYEE_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DEPARTMENT_ID` INT NOT NULL,
    `FIRST_NAME` VARCHAR(100) NOT NULL,
    `LAST_NAME` VARCHAR(100) NOT NULL,
    `ADDRESS` VARCHAR(255),
    `CONTACT_NUMBER` VARCHAR(20),
    `POSITION` VARCHAR(50) NOT NULL,
    `HIRE_DATE` DATE NOT NULL,
    `LAST_LOGIN_DATE` DATETIME,
    
    CONSTRAINT `FK_EMP_DEPT` FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENT`(`DEPARTMENT_ID`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `USER_ACCOUNT`;
CREATE TABLE `USER_ACCOUNT` (
    `USER_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `EMPLOYEE_ID` INT NOT NULL UNIQUE,
    `USERNAME` VARCHAR(50) NOT NULL UNIQUE,
    `PASSWORD_HASH` VARCHAR(255) NOT NULL,
    `ROLE` VARCHAR(50) NOT NULL,
    `ASSIGNED_BRANCH` VARCHAR(100),
    
    CONSTRAINT `FK_USER_EMP` FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE`(`EMPLOYEE_ID`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE `CUSTOMER` (
    `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ACCOUNT_NUMBER` VARCHAR(50) NOT NULL UNIQUE,
    `FIRST_NAME` VARCHAR(100) NOT NULL,
    `LAST_NAME` VARCHAR(100) NOT NULL,
    `STREET` VARCHAR(255) NOT NULL,
    `CITY` VARCHAR(100),
    `PROVINCE` VARCHAR(100),
    `ZIP_CODE` VARCHAR(10),
    `CONTACT_NUMBER` VARCHAR(20) NOT NULL,
    `CREATED_DATE` DATE NOT NULL,
    `BILLING_STATUS` VARCHAR(20) NOT NULL DEFAULT 'PENDING' -- Initial status before meter assignment [cite: 221]
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `METER`;
CREATE TABLE `METER` (
    `METER_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `UTILITY_TYPE_ID` INT NOT NULL,
    `METER_SERIAL_NUMBER` VARCHAR(100) NOT NULL UNIQUE,
    `METER_STATUS` VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    
    CONSTRAINT `FK_METER_UTILITY` FOREIGN KEY (`UTILITY_TYPE_ID`) REFERENCES `REF_UTILITY_TYPE`(`UTILITY_TYPE_ID`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `RATE`;
CREATE TABLE `RATE` (
    `RATE_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `UTILITY_TYPE_ID` INT NOT NULL,
    `RATE_PER_UNIT` DECIMAL(10, 4) NOT NULL,
    `EFFECTIVE_DATE` DATE NOT NULL,
    
    CONSTRAINT `FK_RATE_UTILITY` FOREIGN KEY (`UTILITY_TYPE_ID`) REFERENCES `REF_UTILITY_TYPE`(`UTILITY_TYPE_ID`),
    UNIQUE KEY `UQ_RATE_TYPE_DATE` (`UTILITY_TYPE_ID`, `EFFECTIVE_DATE`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `CONSUMPTION`;
CREATE TABLE `CONSUMPTION` (
    `CONSUMPTION_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `METER_ID` INT NOT NULL,
    `CONSUMPTION_VALUE` DECIMAL(10, 2) NOT NULL,
    `READING_DATE` DATE NOT NULL,
    `BILLING_PERIOD` VARCHAR(20),
    
    CONSTRAINT `FK_CONSUMP_METER` FOREIGN KEY (`METER_ID`) REFERENCES `METER`(`METER_ID`)
) ENGINE=InnoDB;


-- 3. TRANSACTION RECORDS (T9 - T12)

DROP TABLE IF EXISTS `METER_ASSIGNMENT`;
CREATE TABLE `METER_ASSIGNMENT` (
    `ASSIGNMENT_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CUSTOMER_ID` INT NOT NULL,
    `METER_ID` INT NOT NULL UNIQUE,
    `ASSIGNMENT_DATE` DATE NOT NULL,
    `INSTALLATION_DATE` DATE,
    `ASSIGNED_BY_USER_ID` INT NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- Status of the assignment itself [cite: 216]
    `LAST_UPDATED` DATETIME,
    
    CONSTRAINT `FK_ASSIGN_CUST` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`),
    CONSTRAINT `FK_ASSIGN_METER` FOREIGN KEY (`METER_ID`) REFERENCES `METER`(`METER_ID`),
    CONSTRAINT `FK_ASSIGN_USER` FOREIGN KEY (`ASSIGNED_BY_USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `BILL`;
CREATE TABLE `BILL` (
    `BILL_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CUSTOMER_ID` INT NOT NULL,
    `CONSUMPTION_ID` INT NOT NULL UNIQUE,
    `RATE_ID` INT NOT NULL,
    `AMOUNT_DUE` DECIMAL(10, 2) NOT NULL,
    `DUE_DATE` DATE NOT NULL,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'UNPAID', -- Possible values: UNPAID [cite: 244], PAID [cite: 239], PARTIALLY_PAID [cite: 239], OVERPAID [cite: 239], OVERDUE [cite: 249]
    `GENERATED_BY_USER_ID` INT NOT NULL,
    `TECHNICIAN_ID` INT,
    
    CONSTRAINT `FK_BILL_CUST` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`),
    CONSTRAINT `FK_BILL_CONSUMP` FOREIGN KEY (`CONSUMPTION_ID`) REFERENCES `CONSUMPTION`(`CONSUMPTION_ID`),
    CONSTRAINT `FK_BILL_RATE` FOREIGN KEY (`RATE_ID`) REFERENCES `RATE`(`RATE_ID`),
    CONSTRAINT `FK_BILL_USER` FOREIGN KEY (`GENERATED_BY_USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`),
    CONSTRAINT `FK_BILL_TECH` FOREIGN KEY (`TECHNICIAN_ID`) REFERENCES `EMPLOYEE`(`EMPLOYEE_ID`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `PAYMENT_RECEIPT`;
CREATE TABLE `PAYMENT_RECEIPT` (
    `PAYMENT_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `BILL_ID` INT NOT NULL,
    `PAYMENT_DATE` DATETIME NOT NULL,
    `AMOUNT_PAID` DECIMAL(10, 2) NOT NULL,
    `PAYMENT_METHOD` VARCHAR(50) NOT NULL,
    `RECEIPT_NUMBER` VARCHAR(100) NOT NULL UNIQUE,
    `PROCESSED_BY_USER_ID` INT NOT NULL,
    `COLLECTOR_ID` INT,
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'SUCCESS', -- Status of the payment processing event [cite: 234]
    
    CONSTRAINT `FK_PAYMENT_BILL` FOREIGN KEY (`BILL_ID`) REFERENCES `BILL`(`BILL_ID`),
    CONSTRAINT `FK_PAYMENT_USER` FOREIGN KEY (`PROCESSED_BY_USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`),
    CONSTRAINT `FK_PAYMENT_COLL` FOREIGN KEY (`COLLECTOR_ID`) REFERENCES `EMPLOYEE`(`EMPLOYEE_ID`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `OVERDUE_NOTICE`;
CREATE TABLE `OVERDUE_NOTICE` (
    `NOTICE_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `BILL_ID` INT NOT NULL,
    `OVERDUE_DATE` DATE NOT NULL,
    `PENALTY_AMOUNT` DECIMAL(10, 2) NOT NULL,
    `NOTICE_DATE` DATE NOT NULL,
    `ESCALATION_STATUS` VARCHAR(50) NOT NULL DEFAULT 'LEVEL_1', -- Starting level for overdue escalation [cite: 243]
    `SENT_BY_USER_ID` INT NOT NULL,
    
    CONSTRAINT `FK_NOTICE_BILL` FOREIGN KEY (`BILL_ID`) REFERENCES `BILL`(`BILL_ID`),
    CONSTRAINT `FK_NOTICE_USER` FOREIGN KEY (`SENT_BY_USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`),
    UNIQUE KEY `UQ_NOTICE_BILL_DATE` (`BILL_ID`, `OVERDUE_DATE`) 
) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS = 1;